#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okul.Arayuz
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="okul")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdersler(dersler instance);
    partial void Updatedersler(dersler instance);
    partial void Deletedersler(dersler instance);
    partial void Insertsiniflar(siniflar instance);
    partial void Updatesiniflar(siniflar instance);
    partial void Deletesiniflar(siniflar instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Okul.Arayuz.Properties.Settings.Default.okulConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dersler> derslers
		{
			get
			{
				return this.GetTable<dersler>();
			}
		}
		
		public System.Data.Linq.Table<sinifDersleri> sinifDersleris
		{
			get
			{
				return this.GetTable<sinifDersleri>();
			}
		}
		
		public System.Data.Linq.Table<siniflar> siniflars
		{
			get
			{
				return this.GetTable<siniflar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dersler")]
	public partial class dersler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dersId;
		
		private string _dersAdi;
		
		private string _dersOgretmeni;
		
		private string _dersAciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndersIdChanging(int value);
    partial void OndersIdChanged();
    partial void OndersAdiChanging(string value);
    partial void OndersAdiChanged();
    partial void OndersOgretmeniChanging(string value);
    partial void OndersOgretmeniChanged();
    partial void OndersAciklamaChanging(string value);
    partial void OndersAciklamaChanged();
    #endregion
		
		public dersler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dersId
		{
			get
			{
				return this._dersId;
			}
			set
			{
				if ((this._dersId != value))
				{
					this.OndersIdChanging(value);
					this.SendPropertyChanging();
					this._dersId = value;
					this.SendPropertyChanged("dersId");
					this.OndersIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersAdi", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dersAdi
		{
			get
			{
				return this._dersAdi;
			}
			set
			{
				if ((this._dersAdi != value))
				{
					this.OndersAdiChanging(value);
					this.SendPropertyChanging();
					this._dersAdi = value;
					this.SendPropertyChanged("dersAdi");
					this.OndersAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersOgretmeni", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string dersOgretmeni
		{
			get
			{
				return this._dersOgretmeni;
			}
			set
			{
				if ((this._dersOgretmeni != value))
				{
					this.OndersOgretmeniChanging(value);
					this.SendPropertyChanging();
					this._dersOgretmeni = value;
					this.SendPropertyChanged("dersOgretmeni");
					this.OndersOgretmeniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersAciklama", DbType="VarChar(50)")]
		public string dersAciklama
		{
			get
			{
				return this._dersAciklama;
			}
			set
			{
				if ((this._dersAciklama != value))
				{
					this.OndersAciklamaChanging(value);
					this.SendPropertyChanging();
					this._dersAciklama = value;
					this.SendPropertyChanged("dersAciklama");
					this.OndersAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sinifDersleri")]
	public partial class sinifDersleri
	{
		
		private int _dersId;
		
		private int _sinifId;
		
		public sinifDersleri()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dersId", DbType="Int NOT NULL")]
		public int dersId
		{
			get
			{
				return this._dersId;
			}
			set
			{
				if ((this._dersId != value))
				{
					this._dersId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinifId", DbType="Int NOT NULL")]
		public int sinifId
		{
			get
			{
				return this._sinifId;
			}
			set
			{
				if ((this._sinifId != value))
				{
					this._sinifId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.siniflar")]
	public partial class siniflar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sinifId;
		
		private System.Nullable<byte> _sinif;
		
		private string _sube;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsinifIdChanging(int value);
    partial void OnsinifIdChanged();
    partial void OnsinifChanging(System.Nullable<byte> value);
    partial void OnsinifChanged();
    partial void OnsubeChanging(string value);
    partial void OnsubeChanged();
    #endregion
		
		public siniflar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinifId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sinifId
		{
			get
			{
				return this._sinifId;
			}
			set
			{
				if ((this._sinifId != value))
				{
					this.OnsinifIdChanging(value);
					this.SendPropertyChanging();
					this._sinifId = value;
					this.SendPropertyChanged("sinifId");
					this.OnsinifIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinif", DbType="TinyInt")]
		public System.Nullable<byte> sinif
		{
			get
			{
				return this._sinif;
			}
			set
			{
				if ((this._sinif != value))
				{
					this.OnsinifChanging(value);
					this.SendPropertyChanging();
					this._sinif = value;
					this.SendPropertyChanged("sinif");
					this.OnsinifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sube", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string sube
		{
			get
			{
				return this._sube;
			}
			set
			{
				if ((this._sube != value))
				{
					this.OnsubeChanging(value);
					this.SendPropertyChanging();
					this._sube = value;
					this.SendPropertyChanged("sube");
					this.OnsubeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
